import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { Providers } from "./Providers";
import { CartProvider } from "./context/CartContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-row">
        <Providers>
          <CartProvider>
            <div className="h-lvh">
              <Sidebar />
            </div>
            <div className="flex justify-center items-center w-full">
              {children}
            </div>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
